### ISSUE TITLE
[DOC] - Updates to Getting started  guide

### ISSUE THREAD

**Issue by askulkarni2** [aws-quickstart/cdk-eks-blueprints#326]
https://aws-quickstart.github.io/cdk-eks-blueprints/getting-started/#project-setup should be 

```
brew install make
brew install node
```

**Comment by askulkarni2** [comment]
https://aws-quickstart.github.io/cdk-eks-blueprints/getting-started/#project-setup should be 

```
brew install make
brew install node
```

**Comment by askulkarni2** [comment]
For the code here https://aws-quickstart.github.io/cdk-eks-blueprints/getting-started/#deploy-a-blueprint-eks-cluster
```
▶ cdk bootstrap                            

/Users/kuapoorv/scratch/my-blueprints/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
bin/my-blueprints.ts:25:13 - error TS2345: Argument of type 'ClusterAddOn[]' is not assignable to parameter of type 'ClusterAddOn'.
  Property 'deploy' is missing in type 'ClusterAddOn[]' but required in type 'ClusterAddOn'.

25     .addOns(addOns)
               ~~~~~~

  node_modules/@aws-quickstart/eks-blueprints/dist/spi/addon-contracts.d.ts:17:5
    17     deploy(clusterInfo: types.ClusterInfo): Promise<Construct> | void;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'deploy' is declared here.

    at createTSError (/Users/kuapoorv/scratch/my-blueprints/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/kuapoorv/scratch/my-blueprints/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/kuapoorv/scratch/my-blueprints/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/kuapoorv/scratch/my-blueprints/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/kuapoorv/scratch/my-blueprints/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/kuapoorv/scratch/my-blueprints/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
Subprocess exited with error 1
```

Fix is to use the spread operator.

```ts
blueprints.EksBlueprint.builder()
    .account(account)
    .region(region)
    .addOns(...addOns)
    .build(app, 'eks-blueprint');
```

**Comment by shapirov103** [comment]
addressed with https://github.com/aws-quickstart/cdk-eks-blueprints/pull/341
