### ISSUE TITLE
cdk-eks-blueprints release should keep track latest CDK version as much as possible

### ISSUE THREAD

**Issue by vumdao** [aws-quickstart/cdk-eks-blueprints#423]
### Describe the feature

The cdk-eks-blueprints latets release `1.0.2` still keeps CDK version `2.25.0` although the latest version is `2.29.0`

### Use Case

I want to use latest updates of all AWS contructs from CDK

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.25.0

### EKS Blueprints Version

1.0.2

### Node.js Version

v16.13.0

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by vumdao** [comment]
@shapirov103 If I use CDK version different from the version specified in [package.json](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/package.json) I will get following error 
```
TSError: ⨯ Unable to compile TypeScript:
src/main.ts(74,9): error TS2322: Type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/vpc").IVpc' is not assignable to type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/vpc").IVpc'.
  Types of property 'publicSubnets' are incompatible.
    Type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/vpc").ISubnet[]' is not assignable to type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/vpc").ISubnet[]'.
      Type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/vpc").ISubnet' is not assignable to type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/vpc").ISubnet'.
        Types of property 'associateNetworkAcl' are incompatible.
          Type '(id: string, acl: import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/network-acl").INetworkAcl) => void' is not assignable to type '(id: string, acl: import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/network-acl").INetworkAcl) => void'.
            Types of parameters 'acl' and 'acl' are incompatible.
              Type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/network-acl").INetworkAcl' is not assignable to type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/network-acl").INetworkAcl'.
                The types of 'addEntry(...).stack.tags' are incompatible between these types.
                  Type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/core/lib/tag-manager").TagManager' is not assignable to type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/core/lib/tag-manager").TagManager'.
                    Types have separate declarations of a private property 'tags'.
src/main.ts(83,9): error TS2322: Type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/vpc").IVpc' is not assignable to type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/vpc").IVpc'.
src/main.ts(84,9): error TS2322: Type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/security-group").ISecurityGroup' is not assignable to type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/security-group").ISecurityGroup'.
  Types of property 'addIngressRule' are incompatible.
    Type '(peer: import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/peer").IPeer, connection: import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/port...' is not assignable to type '(peer: import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/peer").IPeer, connection: import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/port").Port, description?: string | undefined, remoteRule?: boolean | undefined) => void'.
      Types of parameters 'peer' and 'peer' are incompatible.
        Type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/peer").IPeer' is not assignable to type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/peer").IPeer'.
          The types of 'connections.defaultPort' are incompatible between these types.
            Type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/port").Port | undefined' is not assignable to type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/port").Port | undefined'.
              Type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/port").Port' is not assignable to type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/port").Port'.
                Types have separate declarations of a private property 'props'.
src/main.ts(103,9): error TS2322: Type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/security-group").ISecurityGroup' is not assignable to type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/security-group").ISecurityGroup'.
src/main.ts(104,9): error TS2322: Type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/vpc").IVpc' is not assignable to type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/vpc").IVpc'.
src/main.ts(136,9): error TS2322: Type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/security-group").ISecurityGroup' is not assignable to type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/security-group").ISecurityGroup'.
src/main.ts(137,9): error TS2322: Type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/vpc").IVpc' is not assignable to type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/vpc").IVpc'.
src/main.ts(144,9): error TS2322: Type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/security-group").ISecurityGroup' is not assignable to type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/security-group").ISecurityGroup'.
src/main.ts(145,9): error TS2322: Type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/vpc").IVpc' is not assignable to type 'import("/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/aws-cdk-lib/aws-ec2/lib/vpc").IVpc'.

    at createTSError (/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/home/jack/workspace/gitlab/aws-eks-blueprints-cdk/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

Subprocess exited with error 1
```

**Comment by shapirov103** [comment]
@vumdao as I mentioned in the previous message, you should be able to leverage the "overrides" support similar to the example the I provided in your package.json:

```
"dependencies": {   
...
    "aws-cdk": "2.29.0",
  },
  "overrides": {
    "aws-cdk": "2.29.0"
  }
```

If you apply such an update consider running the following to clear your caches:

```
rm -rf node_modules
rm package-lock.json
npm i
```
Run `npx cdk --version` to make sure the right version of cdk is used in the project.

Also if you use `alias cdk="npx cdk"` in your bashrc/zshrc you won't need to install CDK locally.

**Comment by vumdao** [comment]
@shapirov103 I'm using `projen` and not sure if I did all things correct. I add `override` as following to `package.json`
```
  "overrides": {
    "aws-cdk": "$aws-cdk",
    "aws-cdk-lib": "$aws-cdk-lib"
  },
```

Run
```
rm -rf node_modules
rm package-lock.json
rm package.json
projen
```

The `@aws-quickstart/eks-blueprints`  still contains `aws-cdk-lib` version `2.25.0`

My workaround solution: Override `aws-cdk-lib` manually then it works
