### ISSUE TITLE
[Karpenter] Upgrade to karpenter latest version failed

### ISSUE THREAD

**Issue by vumdao** [aws-quickstart/cdk-eks-blueprints#569]
### Describe the bug

I upgrade karpenter to v0.22.1 and got following error
```
Received response status [FAILED] from custom resource. Message returned: Error: b'\nCould not connect to the endpoint URL: "https://api.ecr-public.ap-south-1.amazonaws.com/"\nLogin Succeeded\nError: public.ecr.aws/karpenter/karpenter:0.22.1: not found\n' Logs: /aws/lambda/DeployDevelop-mmb-vc-d2-qa-eks-blu-Handler886CB40B-Usdx1HkN3nMo at invokeUserFunction (/var/task/framework.js:2:6) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async onEvent (/var/task/framework.js:1:365) at async Runtime.handler (/var/task/cfn-response.js:1:1543) (RequestId: bc3d1ecf-5228-4788-b2c5-4d441a8cd887)
```

### Expected Behavior

Upgrade successfully 

### Current Behavior

Upgrade failed

### Reproduction Steps

Upgrade karpenter from 0.16.0 to 0.22.1 not in us-east-1 region

### Possible Solution

Maybe the URL is 
```
public.ecr.aws/karpenter/karpenter:v0.22.1
```

### CDK CLI Version

2.60.0

### EKS Blueprints Version

1.5.3

### Node.js Version

v18.9.1

### Environment details (OS name and version, etc.)

MacOS 13.1

**Comment by vumdao** [comment]
My wrong define version, it is `v0.22.1` instead of `0.22.1`
