### ISSUE TITLE
JupyterHubAddOn: CLUSTERIP requires AwsLoadBalancerControllerAddOn

### ISSUE THREAD

**Issue by aliaksei-ivanou** [aws-quickstart/cdk-eks-blueprints#616]
### Describe the bug

JupyterHubAddOn JupyterHubServiceType.CLUSTERIP has an unnecessary dependency on AwsLoadBalancerControllerAddOn.

### Expected Behavior

Remove AwsLoadBalancerControllerAddOn as a dependency

### Current Behavior

Dependency on AwsLoadBalancerControllerAddOn

### Code:
```
import * as blueprints from "@aws-quickstart/eks-blueprints";
import {
  EksBlueprint,
  GlobalResources
} from "@aws-quickstart/eks-blueprints";
import { RemovalPolicy } from "aws-cdk-lib";
import * as kms from "aws-cdk-lib/aws-kms";
import { Construct } from "constructs";

const gitUrl =
  "https://github.com/aliaksei-ivanou/eks-blueprints-workloads.git";
const targetRevision = "efs-encryption-at-rest";

export default class DataAtRestEncryptionConstruct {
  build(scope: Construct, id: string) {
    const stackId = `${id}-blueprint`;

    const kmsKey = blueprints.getNamedResource(
      blueprints.GlobalResources.KmsKey
    ) as kms.Key;

    EksBlueprint.builder()
      .resourceProvider(GlobalResources.KmsKey, new blueprints.KmsKeyProvider())
      .addOns(
        new blueprints.JupyterHubAddOn({
          serviceType: blueprints.JupyterHubServiceType.CLUSTERIP,
          efsConfig: {
            removalPolicy: RemovalPolicy.DESTROY,
            pvcName: "jupyterhub-efs-pvc",
            capacity: "10Gi"
          },
        }),
      )
      .teams() // add teams here
      .build(scope, stackId);
  }
}
```

### Error:
```
❯ cdk list
DEBUG Core add-on adot is at version v0.66.0-eksbuild.1
DEBUG Core add-on adot is at version v0.66.0-eksbuild.1
Assertion failed: Unable to auto-detect cluster autoscaler version. Applying latest. Provided EKS cluster version: 1.21
DEBUG Core add-on adot is at version v0.66.0-eksbuild.1
Assertion failed: Unable to auto-detect cluster autoscaler version. Applying latest. Provided EKS cluster version: 1.21
DEBUG Core add-on vpc-cni is at version v1.12.2-eksbuild.1
DEBUG Core add-on coredns is at version v1.8.7-eksbuild.4
DEBUG Core add-on kube-proxy is at version v1.24.7-eksbuild.2
DEBUG Core add-on aws-ebs-csi-driver is at version v1.16.0-eksbuild.1
DEBUG Core add-on adot is at version v0.66.0-eksbuild.1
DEBUG Core add-on vpc-cni is at version v1.12.2-eksbuild.1
DEBUG Core add-on coredns is at version v1.8.7-eksbuild.4
DEBUG Core add-on aws-ebs-csi-driver is at version v1.16.0-eksbuild.1
DEBUG Core add-on kube-proxy is at version v1.24.7-eksbuild.2
/Users/ivanou/Work/forks/cdk-eks-blueprints-patterns/node_modules/@aws-quickstart/eks-blueprints/lib/utils/addon-utils.ts:35
      addOns.forEach( (addOn) => {
             ^
AssertionError [ERR_ASSERTION]: Missing a dependency for AwsLoadBalancerControllerAddOn for data-at-rest-encryption-blueprint
    at /Users/ivanou/Work/forks/cdk-eks-blueprints-patterns/node_modules/@aws-quickstart/eks-blueprints/lib/utils/addon-utils.ts:37:9
    at Array.forEach (<anonymous>)
    at JupyterHubAddOn.descriptor.value (/Users/ivanou/Work/forks/cdk-eks-blueprints-patterns/node_modules/@aws-quickstart/eks-blueprints/lib/utils/addon-utils.ts:35:14)
    at new EksBlueprint (/Users/ivanou/Work/forks/cdk-eks-blueprints-patterns/node_modules/@aws-quickstart/eks-blueprints/lib/stacks/eks-blueprint-stack.ts:263:34)
    at BlueprintBuilder.build (/Users/ivanou/Work/forks/cdk-eks-blueprints-patterns/node_modules/@aws-quickstart/eks-blueprints/lib/stacks/eks-blueprint-stack.ts:195:16)
    at DataAtRestEncryptionConstruct.build (/Users/ivanou/Work/forks/cdk-eks-blueprints-patterns/lib/security/data-at-rest-encryption/index.ts:77:8)
    at Object.<anonymous> (/Users/ivanou/Work/forks/cdk-eks-blueprints-patterns/bin/main.ts:183:33)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .js] (/Users/ivanou/Work/forks/cdk-eks-blueprints-patterns/node_modules/ts-node/src/index.ts:1608:43) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

Subprocess exited with error 1
```

### CDK CLI Version

1.6.0

### Node.js Version

v18.12.1

### Environment details (OS name and version, etc.)

macOS 13.2.1 (22D68)

**Comment by youngjeong46** [comment]
@aliaksei-ivanou This one is merged and released as part of 1.7.x. Will close the issue, but feel free to re-open if issues persist.
