### ISSUE TITLE
Cluster provider context: setting instance type via cdk.json

### ISSUE THREAD

**Issue by yegortokmakov** [aws-quickstart/cdk-eks-blueprints#653]
### Describe the bug

Setting instance type in cdk.json file `"eks.default.instance-type": "m5.4xlarge"` causes troubles as the code relies on ec2.InstanceType instance. 

### Expected Behavior

Using context from JSON file to work in a similar way as `app.node.setContext("eks.default.instance-type", ec2.InstanceType.of(ec2.InstanceClass.M5, ec2.InstanceSize.XLARGE4));`.

### Current Behavior

String representation causes errors in [eks.NodeGroup.getPossibleAmiTypes()](https://github.com/aws/aws-cdk/blob/aa30a30e3fdbcfd9d8732b10b694cc32211d75cf/packages/aws-cdk-lib/aws-eks/lib/managed-nodegroup.ts#L490):
```
TypeError: Cannot read properties of undefined (reading '0')
    at new Nodegroup (cdk/node_modules/aws-cdk-lib/aws-eks/lib/managed-nodegroup.js:1:3930)
    at Cluster.addNodegroupCapacity (cdk/node_modules/aws-cdk-lib/aws-eks/lib/cluster.js:1:17361)
    at MngClusterProvider.addManagedNodeGroup (cdk/node_modules/@aws-quickstart/eks-blueprints/lib/cluster-providers/generic-cluster-provider.ts:370:32)
    at cdk/node_modules/@aws-quickstart/eks-blueprints/lib/cluster-providers/generic-cluster-provider.ts:236:36
    at Array.forEach (<anonymous>)
    at MngClusterProvider.createCluster (cdk/node_modules/@aws-quickstart/eks-blueprints/lib/cluster-providers/generic-cluster-provider.ts:235:39)
    at new EksBlueprint (cdk/node_modules/@aws-quickstart/eks-blueprints/lib/stacks/eks-blueprint-stack.ts:246:44)
    at BlueprintBuilder.build (cdk/node_modules/@aws-quickstart/eks-blueprints/lib/stacks/eks-blueprint-stack.ts:195:16)
    at new VpcEksProviderStack (cdk/lib/vpcEksProvider-stack.ts:55:49)
    at Object.<anonymous> (cdk/bin/galaxy.ts:22:29)
```

### Reproduction Steps

In fresh blueprint deployment add `"eks.default.instance-type": "m5.4xlarge"`  to `cdk.json` and run `cdk deploy`.

### Possible Solution

Check if context provides String type and recreate an instance of ec2.InstanceType in https://github.com/aws-quickstart/cdk-eks-blueprints/blob/f51c11337607ccd3c0bc98295ab2ce84a77d322d/lib/cluster-providers/generic-cluster-provider.ts#L210

### CDK CLI Version

2.74.0 (build 70e2a33)

### EKS Blueprints Version

1.6.1

### Node.js Version

v19.8.1

### Environment details (OS name and version, etc.)

21.6.0 Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64 x86_64

**Comment by shapirov103** [comment]
Addressed by #654
