### ISSUE TITLE
AwsAuthmanifest: onfigmap/aws-auth configured\nerror: error retrieving RESTMappings to prune: invalid resource batch/v1beta1, Kind=CronJob, Namespaced=true: no matches for kind "CronJob" in version "batch/v1beta1" when upgrading from 1.7.3 --> 1.8.1

### ISSUE THREAD

**Issue by chrisdrobison** [aws-quickstart/cdk-eks-blueprints#713]
### Describe the bug

Upgraded our blueprint from 1.7.3 to 1.8.1 without changing anything else and am getting the following error on the AwsAuthmanifest resource:

```
Received response status [FAILED] from custom resource. Message returned: Error: b'configmap/aws-auth configured\nerror: error retrieving RESTMappings to prune: invalid resource batch/v1beta1, Kind=CronJob, Namespaced=true: no matches for kind "CronJob" in version "batch/v1beta1"\n' Logs: /aws/lambda/cognuro-eks-cluster-stack-awscdkaw-Handler886CB40B-Sx96Q9SXHp4I at invokeUserFunction (/var/task/framework.js:2:6) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async onEvent (/var/task/framework.js:1:369) at async Runtime.handler (/var/task/cfn-response.js:1:1573) (RequestId: 124bf82b-e183-4c0c-82fc-d6d05ac9473b)

Logs: /aws/lambda/cognuro-eks-cluster-stack-awscdkaw-Handler886CB40B-Sx96Q9SXHp4I

    at invokeUserFunction (/var/task/framework.js:2:6)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1573) (RequestId: 124bf82b-e183-4c0c-82fc-d6d05ac9473b)
    at FullCloudFormationDeployment.monitorDeployment (/Users/chris/.nvm/versions/node/v16.16.0/lib/node_modules/aws-cdk/lib/index.js:397:10236)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.deployStack2 [as deployStack] (/Users/chris/.nvm/versions/node/v16.16.0/lib/node_modules/aws-cdk/lib/index.js:400:149977)
    at async /Users/chris/.nvm/versions/node/v16.16.0/lib/node_modules/aws-cdk/lib/index.js:400:135508
```

### Expected Behavior

For the upgrade to work without issue

### Current Behavior

Fails with following the error:

```
Received response status [FAILED] from custom resource. Message returned: Error: b'configmap/aws-auth configured\nerror: error retrieving RESTMappings to prune: invalid resource batch/v1beta1, Kind=CronJob, Namespaced=true: no matches for kind "CronJob" in version "batch/v1beta1"\n' Logs: /aws/lambda/cognuro-eks-cluster-stack-awscdkaw-Handler886CB40B-Sx96Q9SXHp4I at invokeUserFunction (/var/task/framework.js:2:6) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async onEvent (/var/task/framework.js:1:369) at async Runtime.handler (/var/task/cfn-response.js:1:1573) (RequestId: 124bf82b-e183-4c0c-82fc-d6d05ac9473b)

Logs: /aws/lambda/cognuro-eks-cluster-stack-awscdkaw-Handler886CB40B-Sx96Q9SXHp4I

    at invokeUserFunction (/var/task/framework.js:2:6)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1573) (RequestId: 124bf82b-e183-4c0c-82fc-d6d05ac9473b)
    at FullCloudFormationDeployment.monitorDeployment (/Users/chris/.nvm/versions/node/v16.16.0/lib/node_modules/aws-cdk/lib/index.js:397:10236)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.deployStack2 [as deployStack] (/Users/chris/.nvm/versions/node/v16.16.0/lib/node_modules/aws-cdk/lib/index.js:400:149977)
    at async /Users/chris/.nvm/versions/node/v16.16.0/lib/node_modules/aws-cdk/lib/index.js:400:135508
```

### Reproduction Steps

1. Changed blueprint dependency from 1.7.3 to 1.8.1
2. `cdk deploy`

Here is the cluster CDK definition:

```
    const blueprint = blueprints.EksBlueprint.builder()
      .account(account)
      .region(region)
      .resourceProvider(blueprints.GlobalResources.Vpc, {
        provide(context): ec2.IVpc {
          return new ec2.Vpc(context.scope, 'vpc', {
            ipAddresses: ec2.IpAddresses.cidr('10.100.0.0/16'),
            natGateways: 1,
          })
        }
      })
      .resourceProvider(hostedZoneName, new blueprints.LookupHostedZoneProvider(hostedZoneName))
      .clusterProvider(new blueprints.GenericClusterProvider({
        version: eks.KubernetesVersion.of('1.26'),
        clusterName: 'cognuro-eks',
        vpcSubnets: [{ subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS }],
        managedNodeGroups: [
          {
            id: 'cognuro-eks-ng-1',
            amiType: eks.NodegroupAmiType.BOTTLEROCKET_X86_64,
            minSize: 1,
            nodeGroupCapacityType: eks.CapacityType.ON_DEMAND,
            instanceTypes: [
              new ec2.InstanceType('t3a.medium'),
            ],
          }
        ],
      }))
      .addOns(
        new blueprints.addons.AwsLoadBalancerControllerAddOn({
          values: {
            replicaCount: 1
          },

        }),
        new blueprints.addons.ExternalDnsAddOn({
          hostedZoneResources: [hostedZoneName],
          values: {
            "policy": "upsert-only",
          }
        }),
        new blueprints.addons.KarpenterAddOn({
          amiFamily: 'Bottlerocket',
          consolidation: {
            enabled: true,
          },
          interruptionHandling: true,
          requirements: [
            { key: 'kubernetes.io/arch', op: 'In', vals: ['amd64'] },
            { key: 'karpenter.sh/capacity-type', op: 'In', vals: ['spot'] },
            { key: 'karpenter.k8s.aws/instance-category', op: 'In', vals: ['t', 'c', 'm', 'r'] },
            { key: 'karpenter.k8s.aws/instance-hypervisor', op: 'In', vals: ['nitro'] },
            { key: 'cognuro.com/default', op: 'In', vals: ['true'] }
          ],
          securityGroupTags: {
            "kubernetes.io/cluster/cognuro-eks": "owned",
          },
          subnetTags: {
            "Name": "cognuro-eks-cluster-stack/vpc/Private*",
          },
          taints: [{
            key: "workload",
            value: "cognuro",
            effect: "NoSchedule",
          }],
          values: {
            replicas: 1,
          },
          version: "v0.27.5",
        }),
        new blueprints.addons.CoreDnsAddOn(),
        new blueprints.addons.EbsCsiDriverAddOn({
          kmsKeys: [
            blueprints.getResource((context) => new Key(context.scope, "ebs-csi-driver-key", {
              alias: "ebs-csi-driver-key",
            }))
          ],
        }),
        new blueprints.addons.KedaAddOn({
          podSecurityContextFsGroup: 1001,
          securityContextRunAsGroup: 1001,
          securityContextRunAsUser: 1001,
          irsaRoles: ["CloudWatchFullAccess", "AmazonSQSFullAccess"],
          namespace: "keda",
        }),
        new blueprints.addons.KubeProxyAddOn(),
        new blueprints.addons.VpcCniAddOn(),
        new blueprints.addons.CertManagerAddOn(),
        new blueprints.addons.AdotCollectorAddOn(),
        new blueprints.addons.NginxAddOn({
          namespace: "nginx"
        }),
      )
      .teams(new blueprints.PlatformTeam({
        name: 'admins',
        users: [
          new ArnPrincipal(`arn:aws:iam::${account}:user/me`),
        ]
      }))
      .useDefaultSecretEncryption(true)
      .build(scope, id + '-stack');
```

### CDK CLI Version

2.81.0

### EKS Blueprints Version

1.8.1

### Node.js Version

v16.16.0

### Environment details (OS name and version, etc.)

MacOS 16.4

**Comment by shapirov103** [comment]
@chrisdrobison was there a cluster version change as well, or just blueprint version change, cluster remaining at 1.26? 
Looks related to https://github.com/aws/aws-cdk/issues/25027.

**Comment by chrisdrobison** [comment]
So do I need to explicitly set the kubectl layer version?

**Comment by shapirov103** [comment]
@chrisdrobison the change that was introduced in the 1.8.x releases: we started setting an explicit kubectl layer for 1.26. Before it was falling back onto 1.25 kubectl layer for EKS version 1.25 and above. That means that you used 1.25 kubectl layer before and it was upgraded to 1.26, which may have caused the issue, which we did not anticipate.

You can try setting the kubectl layer back to 1.25, even though there is a mismatch. 

To do so you you will need to create a subclass of GenericClusterProvider and override the `getKubectlLayer` method, then use this clusterprovider in your blueprint. Here is an example:

```typescript
import { Construct } from 'constructs';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as eks from 'aws-cdk-lib/aws-eks';
import { ILayerVersion } from "aws-cdk-lib/aws-lambda";
import { KubectlV25Layer } from "@aws-cdk/lambda-layer-kubectl-v25";


// Blueprints Lib
import * as blueprints from '@aws-quickstart/eks-blueprints'

// Team implementations
import * as team from '../teams';

class FixedGenericClusterProvider extends blueprints.GenericClusterProvider {

    constructor(readonly props: GenericClusterProviderProps) {
        super(props);
    }
    
   // setting fixed kubectl layer
    protected getKubectlLayer(scope: Construct, version: eks.KubernetesVersion) : ILayerVersion | undefined {
        return new KubectlV25Layer(scope, "kubectllayer25");
    }
}

// instantiate the new cluster provider
const clusterProvider = new FixedGenericClusterProvider({
            version: eks.KubernetesVersion.V1_25,
            managedNodeGroups: [
                {
                    id: "mng-ondemand",
                    amiType: eks.NodegroupAmiType.AL2_X86_64,
                    instanceTypes: [new ec2.InstanceType('m5.2xlarge')]
                },
                {
                    id: "mng2-spot",
                    instanceTypes: [ec2.InstanceType.of(ec2.InstanceClass.BURSTABLE3, ec2.InstanceSize.MEDIUM)],
                    nodeGroupCapacityType: eks.CapacityType.SPOT
                }
            ],
            fargateProfiles: {
                "fp1": {
                    fargateProfileName: "fp1",
                    selectors:  [{ namespace: "serverless1" }] 
                },
                "fp2": {
                    fargateProfileName: "fp2",
                    selectors:  [{ namespace: "serverless2" }] 
                }
            }
        });

blueprints.EksBlueprint.builder()
            .account(accountID)
            .region(process.env.CDK_DEFAULT_REGION!)
            .clusterProvider(clusterProvider) // injecting the FixedGenericClusterProvider
        
```

**Comment by chrisdrobison** [comment]
Ok, I did that and it seems to have gotten past that other error, but now I get the following:

```
Resource handler returned message: "Addon version specified is not supported (Service: Eks, Status Code: 400, Request ID: a87085c8-1553-47ad-9995-0cf1863c2b39)" (RequestToken: cec3999f-fdfd-cdc8-7669-7c9cb17a2c2d, HandlerErrorCode: InvalidRequest)
```

**Comment by chrisdrobison** [comment]
Alright, once I pinned the version, that started working as well. So as far as upgrading the kubectl layer, do I need to maintain that myself going forward or once I upgrade to the 1.26 layer, can I drop this override and fall in with whatever you guys are doing?

**Comment by shapirov103** [comment]
@chrisdrobison We will think holistically about maintaining an automatic match between core addons and EKS versions - that is a common requirement from many customers. 
As far as kubectl layer: I did not expect this failure, hence the version control of kubectl layer was not exposed. 
What we can do now is allow passing the kubectl layer more easily in case it caused problems. This will allow pinning it down. My assumption is that you will be able to drop that code, but as a fallback you will be able to pin it down more easily.
