### ISSUE TITLE
Karpenter invalid code

### ISSUE THREAD

**Issue by NinoSkopac** [aws-quickstart/cdk-eks-blueprints#764]
### Describe the documentation issue

```typescript
const karpenterAddonProps = {
    requirements: [
        { key: 'node.kubernetes.io/instance-type', op: 'In', vals: ['m5.2xlarge'] },
        { key: 'topology.kubernetes.io/zone', op: 'NotIn', vals: ['us-west-2c']},
        { key: 'kubernetes.io/arch', op: 'In', vals: ['amd64','arm64']},
        { key: 'karpenter.sh/capacity-type', op: 'In', vals: ['spot','on-demand']},
    ],
    subnetTags: {
        "Name": "blueprint-construct-dev/blueprint-construct-dev-vpc/PrivateSubnet1",
    },
    securityGroupTags: {
        "kubernetes.io/cluster/blueprint-construct-dev": "owned",
    },
    taints: [{
        key: "workload",
        value: "test",
        effect: "NoSchedule",
    }],
    amiFamily: "AL2",
    amiSelector: {
        "karpenter.sh/discovery/MyClusterName": '*',
    },
    consolidation: { enabled: true },
    ttlSecondsUntilExpired: 2592000,
    weight: 20,
    interruptionHandling: true,
}

const karpenterAddOn = new blueprints.addons.KarpenterAddOn(karpenterAddonProps);
```

I pasted it verbatim and it doesn't work:

```
TSError: ⨯ Unable to compile TypeScript:
bin/my-blueprints.ts:39:61 - error TS2345: Argument of type '{ requirements: { key: string; op: string; vals: string[]; }[]; subnetTags: { Name: string; }; securityGroupTags: { "kubernetes.io/cluster/blueprint-construct-dev": string; }; taints: { key: string; value: string; effect: string; }[]; ... 5 more ...; interruptionHandling: boolean; }' is not assignable to parameter of type 'KarpenterAddOnProps'.
  Types of property 'requirements' are incompatible.
    Type '{ key: string; op: string; vals: string[]; }[]' is not assignable to type '{ key: string; op: "In" | "NotIn"; vals: string[]; }[]'.
      Type '{ key: string; op: string; vals: string[]; }' is not assignable to type '{ key: string; op: "In" | "NotIn"; vals: string[]; }'.
        Types of property 'op' are incompatible.
          Type 'string' is not assignable to type '"In" | "NotIn"'.

39 const karpenterAddOn = new blueprints.addons.KarpenterAddOn(karpenterAddonProps);
```

### Links

https://aws-quickstart.github.io/cdk-eks-blueprints/addons/karpenter/

**Comment by youngjeong46** [comment]
@NinoSkopac Thank you for submitting the issue. Can you kindly share with us the full steps to replicate? Specifically, what version of blueprints npm and CDK are you using to try to deploy?

**Comment by NinoSkopac** [comment]
Hey @youngjeong46 , thank you for responding, I really appreciate it.

Here's my full code:

```typescript
import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import * as blueprints from "@aws-quickstart/eks-blueprints";
import {User} from "@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-iam/lib/user";
import {Port} from "@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/port";

const app = new cdk.App();
const account = 'XXX';
const region = 'us-east-1';

const karpenterAddonProps = {
    requirements: [
        { key: 'node.kubernetes.io/instance-type', op: 'In', vals: ['m5.2xlarge'] },
        { key: 'topology.kubernetes.io/zone', op: 'NotIn', vals: ['us-west-2c']},
        { key: 'kubernetes.io/arch', op: 'In', vals: ['amd64','arm64']},
        { key: 'karpenter.sh/capacity-type', op: 'In', vals: ['spot','on-demand']},
    ],
    subnetTags: {
        "Name": "blueprint-construct-dev/blueprint-construct-dev-vpc/PrivateSubnet1",
    },
    securityGroupTags: {
        "kubernetes.io/cluster/blueprint-construct-dev": "owned",
    },
    taints: [{
        key: "workload",
        value: "test",
        effect: "NoSchedule",
    }],
    amiFamily: "AL2",
    amiSelector: {
        "karpenter.sh/discovery/MyClusterName": '*',
    },
    consolidation: { enabled: true },
    ttlSecondsUntilExpired: 2592000,
    weight: 20,
    interruptionHandling: true,
}

const addOns: Array<blueprints.ClusterAddOn> = [
    new blueprints.addons.AwsLoadBalancerControllerAddOn(),
    new blueprints.addons.ClusterAutoScalerAddOn(),
    new blueprints.addons.CertManagerAddOn(),
    new blueprints.addons.ArgoCDAddOn(),
    new blueprints.addons.CalicoOperatorAddOn(),
    new blueprints.addons.MetricsServerAddOn(),
    new blueprints.addons.VpcCniAddOn(),
    new blueprints.addons.CoreDnsAddOn(),
    new blueprints.addons.KubeProxyAddOn(),
    new blueprints.addons.EbsCsiDriverAddOn(),
    new blueprints.addons.EfsCsiDriverAddOn(),
    new blueprints.addons.KarpenterAddOn(karpenterAddonProps),
];
```

```json
  "dependencies": {
    "@aws-quickstart/eks-blueprints": "^1.6.1",
    "aws-cdk-lib": "^2.79.0",
    "constructs": "^10.0.0",
    "kubernetes-types": "^1.26.0",
    "source-map-support": "^0.5.21"
  }
```

```bash
cdk --version
2.87.0 (build 9fca790)

% npm list
my-blueprints@0.1.0 /Users/user/VisualStudioProjects/project/infra
├── @aws-quickstart/eks-blueprints@1.7.3
├── @types/jest@29.5.1
├── @types/node@18.14.6
├── aws-cdk-lib@2.79.0
├── aws-cdk@2.79.0
├── constructs@10.2.19
├── jest@29.5.0
├── kubernetes-types@1.26.0
├── source-map-support@0.5.21
├── ts-jest@29.1.0
├── ts-node@10.9.1
└── typescript@4.9.5

```

**Comment by youngjeong46** [comment]
@NinoSkopac there might be a version mismatching that is happening. Can you try the following:

1. Change the eks blueprints version to `1.10.0` and cdk version to `2.86.0` on your `package.json` file?
2. Remove and reinstall your dependencies: `rm -rf node_modules && npm i`
3. When you deploy, you may need to use the local install of cdk and not your global: `npx cdk deploy <your stack name>`

**Comment by NinoSkopac** [comment]
Thank you @youngjeong46, this seems promising.

I have an offending line now:
```typescript
// give myself access to the cluster on the website
const adminUser = User.fromUserArn(
    cluster, 'iam_me', "arn:aws:iam::XXX:user/my_username"
);
cluster.getClusterInfo().cluster.awsAuth.addUserMapping(adminUser, {
    groups: ['system:masters'],
})
```

Error is:
```
TSError: ⨯ Unable to compile TypeScript:
bin/my-blueprints.ts:40:34 - error TS2339: Property 'awsAuth' does not exist on type 'ICluster'.
```

Any suggestions?

Cluster is built with 
```typescript
const cluster = blueprints.EksBlueprint.builder()
    .account(account)
    .region(region)
    .addOns(...addOns)
    .useDefaultSecretEncryption(true) // set to false to turn secret encryption off (non-production/demo cases)
    .build(app, 'eks-blueprints-test-cluster');
```

**Comment by paulchambers** [comment]
I ran into this too. You need to do something like:

cluster.getClusterInfo().cluster as cdk.Cluster

So that you can access awsAuth now. (Since 1.10.0?)

**Comment by shapirov103** [comment]
@NinoSkopac the comment from @paulchambers is correct, you need to cast to the eks.Cluster since 1.10 after we added imported cluster. If cluster is imported (pre-existing) then for some reason CDK did not expose the awsAuth capability. 
See https://github.com/aws-quickstart/cdk-eks-blueprints/issues/766#issuecomment-1629210811 for the same.

**Comment by NinoSkopac** [comment]
Thanks guys.


Now I'm getting this
```
TS2694: Namespace '"/.../infra/node_modules/aws-cdk-lib/index"' has no exported member 'Cluster'.
```

My import is
```
import * as cdk from 'aws-cdk-lib';
```

:D

**Comment by NinoSkopac** [comment]
I also tried

```
import {aws_eks} from "aws-cdk-lib";
(cluster.getClusterInfo().cluster as aws_eks.Cluster)
```

Issue is
```
TS2352: Conversion of type 'ICluster' to type 'Cluster' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
```

**Comment by shapirov103** [comment]
@NinoSkopac 

This is mostly around typescript and npm rather than blueprints. Here is an example;

```typescript
import * as blueprints from '@aws-quickstart/eks-blueprints';
import * as cdk from 'aws-cdk-lib';
import * as eks from 'aws-cdk-lib/aws-eks';

const app = new cdk.App();

const b = blueprints.EksBlueprint.builder()
    ...
    .build(app, ...);

const eksCluster: eks.Cluster = b.getClusterInfo().cluster as eks.Cluster;
```

**Comment by NinoSkopac** [comment]
@shapirov103 

Thank you.

Im still getting 

```
Conversion of type 'ICluster' to type 'Cluster' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
```

**Comment by shapirov103** [comment]
the code above worked in our repo, however for strict checking you can make it more explicit as the message suggests:

```typescript
const eksCluster = (b.getClusterInfo().cluster as any) as eks.Cluster;
```

**Comment by NinoSkopac** [comment]
That works, but the main issue remains.

```typescript
const karpenterAddonProps = {
    requirements: [
        { key: 'node.kubernetes.io/instance-type', op: 'In', vals: ['m5.2xlarge'] },
        { key: 'topology.kubernetes.io/zone', op: 'NotIn', vals: ['us-west-2c']},
        { key: 'kubernetes.io/arch', op: 'In', vals: ['amd64','arm64']},
        { key: 'karpenter.sh/capacity-type', op: 'In', vals: ['spot','on-demand']},
    ],
    subnetTags: {
        "Name": "blueprint-construct-dev/blueprint-construct-dev-vpc/PrivateSubnet1",
    },
    securityGroupTags: {
        "kubernetes.io/cluster/blueprint-construct-dev": "owned",
    },
    taints: [{
        key: "workload",
        value: "test",
        effect: "NoSchedule",
    }],
    amiFamily: "AL2",
    amiSelector: {
        "karpenter.sh/discovery/MyClusterName": '*',
    },
    consolidation: { enabled: true },
    ttlSecondsUntilExpired: 2592000,
    weight: 20,
    interruptionHandling: true,
}

const karpenterAddOn = new blueprints.addons.KarpenterAddOn(karpenterAddonProps);
```

Still gives me:

```
TSError: ⨯ Unable to compile TypeScript:
bin/my-blueprints.ts:40:61 - error TS2345: Argument of type '{ requirements: { key: string; op: string; vals: string[]; }[]; subnetTags: { Name: string; }; securityGroupTags: { "kubernetes.io/cluster/blueprint-construct-dev": string; }; taints: { key: string; value: string; effect: string; }[]; ... 5 more ...; interruptionHandling: boolean; }' is not assignable to parameter of type 'KarpenterAddOnProps'.
  Types of property 'taints' are incompatible.
    Type '{ key: string; value: string; effect: string; }[]' is not assignable to type 'Taint[]'.
      Type '{ key: string; value: string; effect: string; }' is not assignable to type 'Taint'.
        Types of property 'effect' are incompatible.
          Type 'string' is not assignable to type '"NoSchedule" | "PreferNoSchedule" | "NoExecute"'.

40 const karpenterAddOn = new blueprints.addons.KarpenterAddOn(karpenterAddonProps);
                                                               ~~~~~~~~~~~~~~~~~~~
```

**Comment by shapirov103** [comment]
@youngjeong46 ^^

**Comment by youngjeong46** [comment]
@NinoSkopac, can you give this a try?

```
const karpenterAddOn = new blueprints.addons.KarpenterAddOn({
  requirements: [
      { key: 'node.kubernetes.io/instance-type', op: 'In', vals: ['m5.2xlarge'] },
      { key: 'topology.kubernetes.io/zone', op: 'NotIn', vals: ['us-west-2c']},
      { key: 'kubernetes.io/arch', op: 'In', vals: ['amd64','arm64']},
      { key: 'karpenter.sh/capacity-type', op: 'In', vals: ['spot','on-demand']},
  ],
  subnetTags: {
    "Name": "blueprint-construct-dev/blueprint-construct-dev-vpc/PrivateSubnet1",
  },
  securityGroupTags: {
    "kubernetes.io/cluster/blueprint-construct-dev": "owned",
  },
  taints: [{
    key: "workload",
    value: "test",
    effect: "NoSchedule",
  }],
  amiFamily: "AL2",
  amiSelector: {
    "karpenter.sh/discovery/MyClusterName": '*',
  },
  consolidation: { enabled: true },
  ttlSecondsUntilExpired: 2592000,
  weight: 20,
  interruptionHandling: true,
});
```

**Comment by NinoSkopac** [comment]
Hey @youngjeong46, I've tested and it deploys - thanks!

I'm not sure if it's working correctly though - isn't it supposed to start m5.2xlarge instances, as it says on the third line?

I'm seeing m5.large being started.

**Comment by NinoSkopac** [comment]
Unfortunately nodes aren't being brought up - my pods are still pending.

I've deleted and recreated the cluster already, as I was migrating from autoscaler addon to karpeneter.

**Comment by youngjeong46** [comment]
I see what's happening - and this is something I'll need to re-update the doc for. 

1. You are seeing `m5.large` instead of `m5.2xlarge` defined in Karpenter: By default, EKS Blueprints will deploy a managed nodegroup with 1 m5.large instance. Karpenter addon uses helm chart to install the tool. The deployment installed will need to run before you can actually use it to scale based on workload requirements. What you are seeing is that node. As defined [here](https://aws.github.io/aws-eks-best-practices/karpenter/#run-the-karpenter-controller-on-eks-fargate-or-on-a-worker-node-that-belongs-to-a-node-group), we recommend running the karpenter pods on a nodegroup or Fargate (and not on nodes managed by Karpenter). By default, when you call `.build()` on EKS Blueprints without a custom cluster provider defined, it will create a managed nodegroup with a default instance type of m5.large and size 1 node (defined in our doc [here](https://aws-quickstart.github.io/cdk-eks-blueprints/cluster-providers/mng-cluster-provider/#configuration), under `desiredSize` and `instanceTypes`.
 
3. You are seeing one of the Karpenter pods pending: By default, Karpenter deploys two replicas - one per node. However, the default nodegroup for EKS Blueprints only provisions one node. That's why you see one of the pod pending.

**Comment by youngjeong46** [comment]
@NinoSkopac Can you try this one? The only difference is we are adding custom value inside our Karpenter addon prop with replica set to 1, so that we only deploy 1 pod.

```
import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import * as blueprints from '@aws-quickstart/eks-blueprints';

const app = new cdk.App();

const karpenterAddOn = new blueprints.addons.KarpenterAddOn({
  requirements: [
      { key: 'node.kubernetes.io/instance-type', op: 'In', vals: ['m5.2xlarge'] },
      { key: 'topology.kubernetes.io/zone', op: 'NotIn', vals: ['us-west-2c']},
      { key: 'kubernetes.io/arch', op: 'In', vals: ['amd64','arm64']},
      { key: 'karpenter.sh/capacity-type', op: 'In', vals: ['spot','on-demand']},
  ],
  subnetTags: {
    "Name": "blueprint-construct-dev/blueprint-construct-dev-vpc/PrivateSubnet1",
  },
  securityGroupTags: {
    "kubernetes.io/cluster/blueprint-construct-dev": "owned",
  },
  taints: [{
    key: "workload",
    value: "test",
    effect: "NoSchedule",
  }],
  amiFamily: "AL2",
  amiSelector: {
    "karpenter.sh/discovery/MyClusterName": '*',
  },
  consolidation: { enabled: true },
  ttlSecondsUntilExpired: 2592000,
  weight: 20,
  interruptionHandling: true,
  values: {
    replicas: 1
  }
});

const blueprint = blueprints.EksBlueprint.builder()
  .addOns(karpenterAddOn)
  .build(app, 'my-stack-name');
```

**Comment by youngjeong46** [comment]
Alternatively, the below defines a cluster provider with 2 nodes:

```
import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import { KubernetesVersion } from 'aws-cdk-lib/aws-eks';
import * as blueprints from '@aws-quickstart/eks-blueprints';

const app = new cdk.App();

const karpenterAddOn = new blueprints.addons.KarpenterAddOn({
  requirements: [
      { key: 'node.kubernetes.io/instance-type', op: 'In', vals: ['m5.2xlarge'] },
      { key: 'topology.kubernetes.io/zone', op: 'NotIn', vals: ['us-west-2c']},
      { key: 'kubernetes.io/arch', op: 'In', vals: ['amd64','arm64']},
      { key: 'karpenter.sh/capacity-type', op: 'In', vals: ['spot','on-demand']},
  ],
  subnetTags: {
    "Name": "blueprint-construct-dev/blueprint-construct-dev-vpc/PrivateSubnet1",
  },
  securityGroupTags: {
    "kubernetes.io/cluster/blueprint-construct-dev": "owned",
  },
  taints: [{
    key: "workload",
    value: "test",
    effect: "NoSchedule",
  }],
  amiFamily: "AL2",
  amiSelector: {
    "karpenter.sh/discovery/MyClusterName": '*',
  },
  consolidation: { enabled: true },
  ttlSecondsUntilExpired: 2592000,
  weight: 20,
  interruptionHandling: true,
});

const clusterProvider = new blueprints.GenericClusterProvider({
  version: KubernetesVersion.V1_25,
  managedNodeGroups: [
    { 
      id:'karpenter-ng',
      desiredSize: 2,
    }
  ]
})

const blueprint = blueprints.EksBlueprint.builder()
  .clusterProvider(clusterProvider)
  .addOns(karpenterAddOn)
  .build(app, 'my-stack-name');
```

**Comment by NinoSkopac** [comment]
The first approach doesn't work - it has no effect even after deleting and then deploying workload pods again.

The second one produces a warning:
```
[Warning at /vividseats-k8/vividseats-k8] You created a cluster with Kubernetes Version 1.25 without specifying the kubectlLayer property. This may cause failures as the kubectl version provided with aws-cdk-lib is 1.20, which is only guaranteed to be compatible with Kubernetes versions 1.19-1.21. Please provide a kubectlLayer from @aws-cdk/lambda-layer-kubectl-v25.
```

And then fails:
```

 ❌ Deployment failed: Error: The stack named project-k8 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: b'configmap/aws-auth configured\nerror: error retrieving RESTMappings to prune: invalid resource batch/v1beta1, Kind=CronJob, Namespaced=true: no matches for kind "CronJob" in version "batch/v1beta1"\n'

Logs: /aws/lambda/project-k8-awscdkawseksKubectlP-Handler886CB40B-DKdtdBbZUPbo

    at invokeUserFunction (/var/task/framework.js:2:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1573) (RequestId: c61480df-cb4c-478b-97b9-4b8b2b4927bf)
    at FullCloudFormationDeployment.monitorDeployment (/Users/ninoskopac/.nvm/versions/node/v18.16.1/lib/node_modules/aws-cdk/lib/index.js:426:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/Users/ninoskopac/.nvm/versions/node/v18.16.1/lib/node_modules/aws-cdk/lib/index.js:429:153208)
    at async /Users/ninoskopac/.nvm/versions/node/v18.16.1/lib/node_modules/aws-cdk/lib/index.js:429:136985

The stack named project-k8 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: b'configmap/aws-auth configured\nerror: error retrieving RESTMappings to prune: invalid resource batch/v1beta1, Kind=CronJob, Namespaced=true: no matches for kind "CronJob" in version "batch/v1beta1"\n'

Logs: /aws/lambda/project-k8-awscdkawseksKubectlP-Handler886CB40B-DKdtdBbZUPbo

    at invokeUserFunction (/var/task/framework.js:2:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1573) (RequestId: c61480df-cb4c-478b-97b9-4b8b2b4927bf)
```

There were no workloads/pods deployed at the time of `cdk deploy`, if that matters.

**Comment by NinoSkopac** [comment]
The first approach doesn't work - it has no effect even after deleting and then deploying workload pods again.

The second one produces a warning:
```
[Warning at /project-k8] You created a cluster with Kubernetes Version 1.25 without specifying the kubectlLayer property. This may cause failures as the kubectl version provided with aws-cdk-lib is 1.20, which is only guaranteed to be compatible with Kubernetes versions 1.19-1.21. Please provide a kubectlLayer from @aws-cdk/lambda-layer-kubectl-v25.
```

And then fails:
```

 ❌ Deployment failed: Error: The stack named project-k8 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: b'configmap/aws-auth configured\nerror: error retrieving RESTMappings to prune: invalid resource batch/v1beta1, Kind=CronJob, Namespaced=true: no matches for kind "CronJob" in version "batch/v1beta1"\n'

Logs: /aws/lambda/project-k8-awscdkawseksKubectlP-Handler886CB40B-DKdtdBbZUPbo

    at invokeUserFunction (/var/task/framework.js:2:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1573) (RequestId: c61480df-cb4c-478b-97b9-4b8b2b4927bf)
    at FullCloudFormationDeployment.monitorDeployment (/Users/ninoskopac/.nvm/versions/node/v18.16.1/lib/node_modules/aws-cdk/lib/index.js:426:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/Users/ninoskopac/.nvm/versions/node/v18.16.1/lib/node_modules/aws-cdk/lib/index.js:429:153208)
    at async /Users/ninoskopac/.nvm/versions/node/v18.16.1/lib/node_modules/aws-cdk/lib/index.js:429:136985

The stack named project-k8 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: b'configmap/aws-auth configured\nerror: error retrieving RESTMappings to prune: invalid resource batch/v1beta1, Kind=CronJob, Namespaced=true: no matches for kind "CronJob" in version "batch/v1beta1"\n'

Logs: /aws/lambda/project-k8-awscdkawseksKubectlP-Handler886CB40B-DKdtdBbZUPbo

    at invokeUserFunction (/var/task/framework.js:2:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async onEvent (/var/task/framework.js:1:369)
    at async Runtime.handler (/var/task/cfn-response.js:1:1573) (RequestId: c61480df-cb4c-478b-97b9-4b8b2b4927bf)
```

There were no workloads/pods of my own deployed at the time of `cdk deploy`, if that matters.

**Comment by youngjeong46** [comment]
can you first destroy the stack, and then re-deploy with the updated code?

**Comment by NinoSkopac** [comment]
Sure - and thank you for sticking with me for so long - on a Saturday no less.

Any suggestion on which approach should I prefer? 
Adding `values: { replica: 1 } ` to addon prop or creating a new cluster provider?

**Comment by NinoSkopac** [comment]
I'm going for the 2nd approach but trying to get rid of the warning as it may be the cause of the issue.

```bash
npm i @aws-cdk/lambda-layer-kubectl-v25
```


```typescript
import {KubectlV25Layer} from'@aws-cdk/lambda-layer-kubectl-v25';
const clusterProvider = new blueprints.GenericClusterProvider({
    version: KubernetesVersion.V1_25,
    managedNodeGroups: [
        {
            id: 'karpenter-ng',
            desiredSize: 2
        }
    ],
    kubectlLayer: new KubectlV25Layer(app, 'kubectl-layer')
});
```

Gives me 
```
TS2322: Type 'KubectlV25Layer' is not assignable to type 'ILayerVersion'.   The types of 'stack.tags' are incompatible between these types.
```

**Comment by NinoSkopac** [comment]
I just upgraded `aws-cdk-lib` from `2.87` to `2.88` using `npm i aws-cdk-lib@latest` and that got rid of the aforementioned type error.

Now I'm getting a new error:
```
Error: KubectlV25Layer at 'kubectl-layer' should be created in the scope of a Stack, but no Stack found
```

**Comment by shapirov103** [comment]
please use CDK 2.88 and blueprints version 1.10.1. Once you set these dependencies in the package.json you can run the following commands to apply:

```
rm -rf node_modules
rm package-lock.json
npm install
```

Then you can use `npx cdk list` and `npx cdk deploy` commands instead of just `cdk` to make sure that you use CDK from the blueprints rather than globally installed. I just create an alias like `alias cdk="npx cdk"`

**Comment by NinoSkopac** [comment]
Thank you @shapirov103 , I've done as you said.

It deployed but karpenter doesn't seem to be working:
- I've deployed a bunch of pods and they're in pending state. 
- New instances aren't being spun up.

A couple of m5.large were created.

Here's my code:
```typescript
import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import * as blueprints from '@aws-quickstart/eks-blueprints';
import {KubernetesVersion} from "aws-cdk-lib/aws-eks";

const app = new cdk.App();
const account = 'XXX';
const region = 'us-east-1';
const clusterName = 'cluster-name';

const karpenterAddOn = new blueprints.addons.KarpenterAddOn({
    requirements: [
        { key: 'node.kubernetes.io/instance-type', op: 'In', vals: ['m5.2xlarge'] },
        { key: 'topology.kubernetes.io/zone', op: 'NotIn', vals: ['us-west-2c']},
        { key: 'kubernetes.io/arch', op: 'In', vals: ['amd64','arm64']},
        { key: 'karpenter.sh/capacity-type', op: 'In', vals: ['spot','on-demand']},
    ],
    subnetTags: {
        "Name": "blueprint-construct-dev/blueprint-construct-dev-vpc/PrivateSubnet1",
    },
    securityGroupTags: {
        "kubernetes.io/cluster/blueprint-construct-dev": "owned",
    },
    taints: [{
        key: "workload",
        value: "test",
        effect: "NoSchedule",
    }],
    amiFamily: "AL2",
    amiSelector: {
        "karpenter.sh/discovery/MyClusterName": '*',
    },
    consolidation: { enabled: true },
    ttlSecondsUntilExpired: 2592000,
    weight: 20,
    interruptionHandling: true,
});
const clusterProvider = new blueprints.GenericClusterProvider({
    version: KubernetesVersion.V1_25,
    managedNodeGroups: [
        {
            id: 'karpenter-ng',
            desiredSize: 2
        }
    ],
});
const addOns: Array<blueprints.ClusterAddOn> = [
    new blueprints.addons.ArgoCDAddOn(),
    new blueprints.addons.CalicoOperatorAddOn(),
    new blueprints.addons.MetricsServerAddOn(),
    new blueprints.addons.AwsLoadBalancerControllerAddOn(),
    new blueprints.addons.VpcCniAddOn(),
    new blueprints.addons.CoreDnsAddOn(),
    new blueprints.addons.KubeProxyAddOn(),
    new blueprints.addons.CloudWatchLogsAddon({
        namespace: 'aws-for-fluent-bit',
        createNamespace: true,
        serviceAccountName: 'aws-fluent-bit-for-cw-sa',
        logGroupPrefix: `/aws/eks/${clusterName}`,
        logRetentionDays: 7
    }),
    karpenterAddOn
];
const stack = blueprints.EksBlueprint.builder()
    .clusterProvider(clusterProvider)
    .account(account)
    .region(region)
    .addOns(...addOns)
    .useDefaultSecretEncryption(true) // set to false to turn secret encryption off (non-production/demo cases)
    .build(app, clusterName);
```

**Comment by NinoSkopac** [comment]
From CW, karpenter log group:

```
{
    "log": "2023-07-24T22:23:24.522480794Z stdout F 2023-07-24T22:23:24.522Z\tERROR\tcontroller\tReconciler error\t{\"commit\": \"26e2d35-dirty\", \"controller\": \"awsnodetemplate\", \"controllerGroup\": \"karpenter.k8s.aws\", \"controllerKind\": \"AWSNodeTemplate\", \"AWSNodeTemplate\": {\"name\":\"default\"}, \"namespace\": \"\", \"name\": \"default\", \"reconcileID\": \"fad73e42-2388-443f-a8fc-253e387a542d\", \"error\": \"no subnets exist given constraints; no security groups exist given constraints; no amis exist given constraints\", \"errorCauses\": [{\"error\": \"no subnets exist given constraints\"}, {\"error\": \"no security groups exist given constraints\"}, {\"error\": \"no amis exist given constraints\"}]}",
    "kubernetes": {
        "pod_name": "karpenter-654c9cdb-r55h8",
        "namespace_name": "karpenter",
        "pod_id": "4cb5cec4-254e-49c3-b082-5b1ed164fbca",
        "labels": {
            "app.kubernetes.io/instance": "karpenter",
            "app.kubernetes.io/name": "karpenter",
            "pod-template-hash": "654c9cdb"
        },
        "annotations": {
            "checksum/settings": "84cc8ff538a84df2080108694cafbae5f4779a356400a3f75129385176eb9b7e"
        },
        "host": "ip-10-0-143-228.ec2.internal",
        "container_name": "controller",
        "docker_id": "e693778e65ed0d74909055f612637f4e1a0f89416dd52de7c4fa6b7dc0730422",
        "container_hash": "public.ecr.aws/karpenter/controller@sha256:4194fc219d5a1019cd8d7d69f518b903e972966cad2e9420ccbe9dca149f179d",
        "container_image": "sha256:75de75cdbdfe1d0f5283abe3793471b742dfe3d0390a7d75520b1d3e06956034"
    }
}
```

**Comment by shapirov103** [comment]
@NinoSkopac the error message that you attached  is quite explanatory: `no subnets exist given constraints; no security groups exist given constraints; no amis exist given constraints`. 
Have you provide correct subnet tags, security group tags and ami selectors?

**Comment by NinoSkopac** [comment]
no sir!

**Comment by NinoSkopac** [comment]
Was i instructed to somewhere?

**Comment by shapirov103** [comment]
Chome link to our [docs](https://aws-quickstart.github.io/cdk-eks-blueprints/addons/karpenter/#:~:text=(Optionally)%20provisions%20a,it%20to%20work). 
Please note, that EKS Blueprints 1/ deploys Karpenter and 2/ optionally provides an approach to create a provisioner. We don't aim to replicate full Karpenter documentation on the EKS Blueprints side, however we are considering adding a pattern to demonstrate how it works.
At the moment, as you might have discovered, using Karpenter with EKS Blueprints requires deeper understanding of the Karpenter configuration options to make it work.  You can read more on the provisioner and Karpenter at the [official doc site](https://karpenter.sh/docs/concepts/provisioners/).

**Comment by NinoSkopac** [comment]
Great, thank you!

**Comment by NinoSkopac** [comment]
> however we are considering adding a pattern to demonstrate how it works

Please do this 🙈

**Comment by NinoSkopac** [comment]
That's great.

Let me ask - do I need to run `make pattern karpenter deploy` ?

It's my understanding it deploys a cluster using karpenter (with the KarpenterConstruct), but I can also just use this code, which seems to be key:

```typescript
        const account = process.env.CDK_DEFAULT_ACCOUNT!;
        const region = process.env.CDK_DEFAULT_REGION!;
        const stackID = `${id}-blueprint`;

        const karpenterAddon = new blueprints.addons.KarpenterAddOn({
            requirements: [
                { key: 'node.kubernetes.io/instance-type', op: 'In', vals: ['m5.large'] },
                { key: 'topology.kubernetes.io/zone', op: 'NotIn', vals: ['us-west-2c']},
                { key: 'kubernetes.io/arch', op: 'In', vals: ['amd64','arm64']},
                { key: 'karpenter.sh/capacity-type', op: 'In', vals: ['on-demand']},
            ],
            subnetTags: {
                "Name": `${stackID}/${stackID}-vpc/*`,
            },
            securityGroupTags: {
                [`kubernetes.io/cluster/${stackID}`]: "owned",
            },
            consolidation: { enabled: true },
            ttlSecondsUntilExpired: 2592000,
            weight: 20,
            interruptionHandling: true,
        });
```

**Comment by shapirov103** [comment]
@NinoSkopac you can either copy paste that code into your project, or if you want to run the pattern as is the please clone the patterns repo and run `make pattern karpetner deploy`.

**Comment by NinoSkopac** [comment]
Great, thank you. 

So the key is using stackID. 

What should the id be?

**Comment by shapirov103** [comment]
> What should the id be?

Anything you want. The stackID is the name of the cloud formation stack that will be created in the target account/region once you deploy. 

E.g. `const id = 'my-karpenter';` 
or you can replace the stackId with `const stackID = 'my-awesome-blueprint';`

**Comment by NinoSkopac** [comment]
It worked!
