### ISSUE TITLE
Unable to lookup provisioned efs file systemid in custom addon

### ISSUE THREAD

**Issue by daniel-pebble** [aws-quickstart/cdk-eks-blueprints#835]
### Describe the bug

cdk can't lookup the fileSystemId as getRequiredResource() states that the efs resource is missing however it is declared 

### Expected Behavior

Stack should deploy and it is possible to lookup the id of the efs file system

### Current Behavior

The following error is return when running cdk deploy

AssertionError [ERR_ASSERTION]: Required resource eks-test-efs is missing.
    at ClusterInfo.getRequiredResource (/mnt/d/Oceans/oceans-templates/eks-blueprint/node_modules/@aws-quickstart/eks-blueprints/lib/spi/types.ts:263:9)
    at DeploymentServiceJob.deploy (/mnt/d/Oceans/oceans-templates/eks-blueprint/bin/eks-blueprint.ts:127:33)
    at new EksBlueprint (/mnt/d/Oceans/oceans-templates/eks-blueprint/node_modules/@aws-quickstart/eks-blueprints/lib/stacks/eks-blueprint-stack.ts:273:34)
    at BlueprintBuilder.build (/mnt/d/Oceans/oceans-templates/eks-blueprint/node_modules/@aws-quickstart/eks-blueprints/lib/stacks/eks-blueprint-stack.ts:201:16)
    at Object.<anonymous> (/mnt/d/Oceans/oceans-templates/eks-blueprint/bin/eks-blueprint.ts:217:6)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module.m._compile (/mnt/d/Oceans/oceans-templates/eks-blueprint/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/mnt/d/Oceans/oceans-templates/eks-blueprint/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

### Reproduction Steps

```
  const efsResourceName = stackName + "-efs";

  export class DeploymentServiceJob implements blueprints.ClusterAddOn {
  @blueprints.utils.dependable(blueprints.EfsCsiDriverAddOn.name)
  deploy(clusterInfo: blueprints.ClusterInfo): void {
      const cluster = clusterInfo.cluster;
      
      const efs = clusterInfo.getRequiredResource<IFileSystem>(efsResourceName);

      const scResource = new KubernetesManifest(clusterInfo.cluster, 'efs-sc', {
          cluster: clusterInfo.cluster,
          manifest: [{
              apiVersion: "storage.k8s.io/v1",
              kind: "StorageClass",
              metadata: { name: "efs-sc" },
              provisioner: "efs.csi.aws.com",
              parameters: {
                  provisioningMode: "efs-ap",
                  fileSystemId: `${efs.fileSystemId}`,
                  directoryPerms: "700",
                  gidRangeStart: "1000",
                  gidRangeEnd: "2000",
                  basePath: "/dynamic_provisioning"
              }
          }], overwrite: true,
      });
  }
}

const stack = blueprints.EksBlueprint.builder()
    .resourceProvider("efs-file-system", new blueprints.CreateEfsFileSystemProvider({name: efsResourceName}))
    .addOns(...addOns)
    .build(app, stackName);

```

### CDK CLI Version

2.9.1

### EKS Blueprints Version

1.11.2

### Node.js Version

18.17.1

### Environment details (OS name and version, etc.)

Ubuntu 20.04

**Comment by daniel-pebble** [comment]
I was using the wrong name to lookup the resource, it should have been "efsResourceName".
I then got this error 
`"Error: TypeError: Cannot read properties of undefined (reading 'then') at /mnt/d/Oceans/oceans-templates/eks-blueprint/node_modules/@aws-quickstart/eks-blueprints/lib/utils/addon-utils.ts:50:31" , `

I was able to fix this by removing the dependable at the top of the class
