### ISSUE TITLE
EKS workshop's lib/my-eks-blueprints-stack.ts needs .version("auto") added to it

### ISSUE THREAD

**Issue by bconner22** [aws-quickstart/cdk-eks-blueprints#857]
### Describe the documentation issue

While following https://catalog.workshops.aws/eks-blueprints-for-cdk/en-US/030-single-eks-cluster/031-create-a-cluster/2-create-a-cluster, I got the following error on `cdk list`:

```
% cdk list
/Users/brian/Documents/my-eks-blueprints/node_modules/@aws-quickstart/eks-blueprints/lib/cluster-providers/generic-cluster-provider.ts:246
            throw new Error("Version was not specified by cluster builder or in cluster provider props, must be specified in one of these");
                  ^
Error: Version was not specified by cluster builder or in cluster provider props, must be specified in one of these
    at MngClusterProvider.createCluster (/Users/brian/Documents/my-eks-blueprints/node_modules/@aws-quickstart/eks-blueprints/lib/cluster-providers/generic-cluster-provider.ts:246:19)
    at new EksBlueprint (/Users/brian/Documents/my-eks-blueprints/node_modules/@aws-quickstart/eks-blueprints/lib/stacks/eks-blueprint-stack.ts:256:44)
    at BlueprintBuilder.build (/Users/brian/Documents/my-eks-blueprints/node_modules/@aws-quickstart/eks-blueprints/lib/stacks/eks-blueprint-stack.ts:201:16)
    at new ClusterConstruct (/Users/brian/Documents/my-eks-blueprints/lib/my-eks-blueprints-stack.ts:18:6)
    at Object.<anonymous> (/Users/brian/Documents/my-eks-blueprints/bin/my-eks-blueprints.ts:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module.m._compile (/Users/brian/Documents/my-eks-blueprints/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/brian/Documents/my-eks-blueprints/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1091:32)

Subprocess exited with error 1
```

I added `    .version("auto")` to the `const blueprint....` and it deployed successfully.

### Links

 https://catalog.workshops.aws/eks-blueprints-for-cdk/en-US/030-single-eks-cluster/031-create-a-cluster/2-create-a-cluster

**Comment by bconner22** [comment]
Just realized I'm on `2.99.1 (build b2a895e)` instead of `aws-cdk@2.91.0` since I was previously trying to use the [Quickstart](https://github.com/aws-quickstart/cdk-eks-blueprints), unsure if that's the issue.

**Comment by youngjeong46** [comment]
@bconner22 You are correct - the workshop versions are a bit behind the official Quickstart (npm v1.11.3 vs v1.12.0, and CDK version 2.91.0 vs 2.99.1). Previous blueprints version did not require specifying the k8s version.

We will incorporate the version configurations on the next workshop update.

**Comment by youngjeong46** [comment]
Update - we are currently updating the workshop to the latest Quickstart version (1.12), and will incorporate this fix. Will continue to update as frequently as needed.

**Comment by youngjeong46** [comment]
@bconner22 - we have updated our workshop to address the issue. Please take a look when you can and reopen if issue persists.

Closing for now.
