### ISSUE TITLE
InstanceType not assignable

### ISSUE THREAD

**Issue by jwilms1971** [aws-quickstart/cdk-eks-blueprints#860]
### Describe the documentation issue

I have defined the following in bin/my-blueprints.ts file:

#!/usr/bin/env node
import * as cdk from 'aws-cdk-lib';
import * as blueprints from '@aws-quickstart/eks-blueprints';
import { KubernetesVersion, NodegroupAmiType } from 'aws-cdk-lib/aws-eks';
import { InstanceType } from 'aws-cdk-lib/aws-ec2';

const app = new cdk.App();
const account = '635859128837';
const region = 'ap-southeast-1';
const version = 'auto';

const clusterProvider = new blueprints.MngClusterProvider({
    version: KubernetesVersion.V1_27,
    desiredSize: 2,
    instanceTypes: [new InstanceType('m5.large')],
    amiType: NodegroupAmiType.BOTTLEROCKET_X86_64,
    minSize: 2,
    maxSize: 5,
    diskSize: 50,
  });

const addOns: Array<blueprints.ClusterAddOn> = [
    new blueprints.addons.ArgoCDAddOn(),
    new blueprints.addons.CalicoOperatorAddOn(),
    new blueprints.addons.MetricsServerAddOn(),
    new blueprints.addons.ClusterAutoScalerAddOn(),
    new blueprints.addons.AwsLoadBalancerControllerAddOn(),
    new blueprints.addons.VpcCniAddOn(),
    new blueprints.addons.CoreDnsAddOn(),
    new blueprints.addons.KubeProxyAddOn()
];

const stack = blueprints.EksBlueprint.builder()
    .account(account)
    .region(region)
    .version(version)
    .addOns(...addOns)
    .clusterProvider(clusterProvider)
    .useDefaultSecretEncryption(true) // set to false to turn secret encryption off (non-production/demo cases)
    .build(app, 'eks-blueprint');

When I run cdk synth (or cdk deploy) I get the following error:

$ cdk synth
/home/jwilms/my-blueprints/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
bin/my-blueprints.ts:15:21 - error TS2322: Type 'import("/home/jwilms/my-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/instance-types").InstanceType' is not assignable to type 'import("/home/jwilms/my-blueprints/node_modules/@aws-quickstart/eks-blueprints/node_modules/aws-cdk-lib/aws-ec2/lib/instance-types").InstanceType'.
  Types have separate declarations of a private property 'instanceTypeIdentifier'.

15     instanceTypes: [new InstanceType('m5.large')],
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/home/jwilms/my-blueprints/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/jwilms/my-blueprints/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/jwilms/my-blueprints/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/jwilms/my-blueprints/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/jwilms/my-blueprints/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/home/jwilms/my-blueprints/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  diagnosticCodes: [ 2322 ]
}

Subprocess exited with error 1

$npm list
my-blueprints@0.1.0 /home/jwilms/my-blueprints
├── @aws-quickstart/eks-blueprints@1.12.0
├── @types/jest@29.5.6
├── @types/node@20.7.1
├── aws-cdk-lib@2.101.1
├── aws-cdk@2.101.1
├── constructs@10.3.0
├── jest@29.7.0
├── source-map-support@0.5.21
├── ts-jest@29.1.1
├── ts-node@10.9.1
└── typescript@5.2.2

As a new cdk user it is not clear how to resolve this. Please advise.

### Links

none

**Comment by jwilms1971** [comment]
version issue. rolled back to cdk2.99.1
