### ISSUE TITLE
BlueprintBuilder: EKS cluster creation fails with VPC Resource Provider having subnets in localzones

### ISSUE THREAD

**Issue by sdpoueme** [aws-quickstart/cdk-eks-blueprints#907]
### Describe the bug

We are trying to build an EKS cluster with two autoscaling node groups (core-nodes-asg and inference-nodes-asg). The ASG core-nodes-asg launches nodes in the region, while the inference-nodes-asg launches nodes in a localzone inside the region. The creation of the cluster fails with an error message stating that there is no capacity available to launch the cluster:

```
Received response status [FAILED] from custom resource. Message returned: Cannot create cluster 'usw-2-test4' because us-
west-2-lax-1a, the targeted availability zone, does not currently have sufficient capacity to support the cluster. Retry
and choose from these availability zones: us-west-2a, us-west-2b, us-west-2c, us-west-2d
```

### Expected Behavior

We expect the EKS control plane to be launched in the region. And each node group to be created in specific subnets within the region. One of the node groups will launch in a subnet that is mapped to the localzone. 

### Current Behavior

Looking in depth, we notice that the blueprint is trying to launch the cluster in a localzone instead of using the region to create the control plane:

```
Logs: /aws/lambda/EksClusterStackedgeinferenc-OnEventHandler42BEBAE0-PApeIABZfBLz

    at de_UnsupportedAvailabilityZoneExceptionRes (/var/runtime/node_modules/@aws-sdk/client-eks/dist-cjs/protocols/Aws_restJson1.js:3293:23)
    at de_CreateClusterCommandError (/var/runtime/node_modules/@aws-sdk/client-eks/dist-cjs/protocols/Aws_restJson1.js:1235:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:30:20
    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async rB.onCreate (/var/task/index.js:63:8513) (RequestId: 6a223997-6843-4f97-b54c-f0cf9f0a35aa)
```

### Reproduction Steps

1. Create a vpc resource provider with azs mapped to the region azs and localzones
```
export class VpcResourceProvider implements ResourceProvider<IVpc> {


    provide(context: ResourceContext): IVpc {
        return new ec2.Vpc(context.scope, 'eks-edge-vpc4', {
            ipAddresses: ec2.IpAddresses.cidr('10.0.0.0/16'),
            natGateways: 0,
            availabilityZones: ['us-west-2a','us-west-2b','us-west-2c'], // VPC spans all AZs
            subnetConfiguration: [ {
                cidrMask: 26,
                name: 'public-eks-subnet',
                subnetType: SubnetType.PUBLIC,
                mapPublicIpOnLaunch: true
            },
                {
                    cidrMask: 26,
                    name: 'private-eks-subnet',
                    subnetType: SubnetType.PRIVATE_WITH_EGRESS
                },

            ]
        });
    }
}
```
3. Create two ASGs to host node groups
```
const nodesProvider = new blueprints.GenericClusterProvider(
            {
                clusterName: cluster_name,
                vpcSubnets: [ {subnetType:ec2.SubnetType.PUBLIC }],
                autoscalingNodeGroups: [
                    {
                        id: "core",
                        autoScalingGroupName: "core-nodes-asg",
                        desiredSize: 3,
                        minSize: 1,
                        maxSize: 3,
                        machineImageType: MachineImageType.AMAZON_LINUX_2
                    },
                    {
                        id: "inference",
                        autoScalingGroupName: "inference-nodes-asg",
                        //instanceType: new ec2.InstanceType('g5.4xlarge'),
                        desiredSize: 3,
                        minSize: 1,
                        maxSize: 3,
                        machineImageType: MachineImageType.AMAZON_LINUX_2,
                        nodeGroupSubnets: {availabilityZones: ['us-west-2-lax-1a', 'us-west-2-lax-1b']}

                    }
                ]
            }
        );
```
5. Build the cluster
```
const stack = blueprints.EksBlueprint.builder()
            .resourceProvider(GlobalResources.Vpc, regionVPC)
            .clusterProvider(nodesProvider)
            .account(account)
            .region(region)
            .version(version)
            .addOns(...addOns)
            .useDefaultSecretEncryption(false) // set to false to turn secret encryption off (non-production/demo cases)
            .build(this, cluster_name);
    }
```
### Possible Solution

During the VPC creation, consider subnets in the localzone. Build the cluster control plane using the region AZs only. Then provide a way to launch ASGs separately after the build process. Also give the ability to launch any ASG in a localzone az. 

### CDK CLI Version

2.115.0

### EKS Blueprints Version

1.13.1

### Node.js Version

v21.4.0

### Environment details (OS name and version, etc.)

Mac OS 14.2.1 (23C71)

**Comment by shapirov103** [comment]
Based on the configuration above, the CP ENIs are created in public subnets. Can you be explicit with respect to the subnets for the control plane, i.e. `vpcSubnets` attribute?

Also for the first node group, I think it makes sense to also set subnets explicitly, if the core nodes asg should be using regional AZs. At the moment this configuration is not specified, it makes sense to enumerate the AZs explicitly for the first node group. 

For the inference node group, you set the desired and min capacity to 1 - is there capacity in the localzone? 

The last question: let's say you remove the inference node group, does the solution work?

**Comment by sdpoueme** [comment]
Thanks for the feedback. I will start by the last question, the solution works when I remove the inference node group. Regarding the AZs should we also list them explicitly in the VPC resource provider when creating the VPC:

**Comment by sdpoueme** [comment]
I followed the recommendations and adjusted the cluster definition. It resolved the issue. 
We have a new definition for the VPC Resource Provider: 
```
export class VpcResourceProvider implements ResourceProvider<IVpc> {

    //'us-west-2-den-1a','us-west-2-las-1a','us-west-2-pdx-1a','us-west-2-phx-2a','us-west-2-sea-1a
    provide(context: ResourceContext): IVpc {
        return new ec2.Vpc(context.scope, 'eks-edge-vpc6', {
            ipAddresses: ec2.IpAddresses.cidr('10.0.0.0/16'),
            natGateways: 0,
            availabilityZones: ['us-west-2-lax-1a', 'us-west-2-lax-1b','us-west-2a','us-west-2b','us-west-2c','us-west-2d'], // VPC spans all AZs
            subnetConfiguration: [ {
                cidrMask: 26,
                name: 'public-eks-subnet',
                subnetType: SubnetType.PUBLIC,
                mapPublicIpOnLaunch: true
            },
                {
                    cidrMask: 26,
                    name: 'private-eks-subnet',
                    subnetType: SubnetType.PRIVATE_WITH_EGRESS
                },

            ]
        });
    }
```
and changed the generic node providers to:

**Comment by sdpoueme** [comment]
Thank you for the recommendations, I will close the issue now. :)
