### ISSUE TITLE
eks-blueprints: Got error when running cdk snapshot test

### ISSUE THREAD

**Issue by vumdao** [aws-quickstart/cdk-eks-blueprints#950]
### Describe the bug

```
  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "DEBUG Core add-on vpc-cni has autoselected version v1.16.0-eksbuild.1".

      at console.log (node_modules/.pnpm/@jest+console@29.7.0/node_modules/@jest/console/build/BufferedConsole.js:156:10)
      at Object.transportFormatted (node_modules/.pnpm/tslog@4.9.2/node_modules/tslog/dist/cjs/runtime/nodejs/index.js:116:13)
      at Logger.log (node_modules/.pnpm/tslog@4.9.2/node_modules/tslog/dist/cjs/BaseLogger.js:118:32)
      at Logger.debug (node_modules/.pnpm/tslog@4.9.2/node_modules/tslog/dist/cjs/index.js:40:22)
      at VpcCniAddOn.provideVersion (node_modules/.pnpm/@aws-quickstart+eks-blueprints@1.14.0_aws-cdk-lib@2.132.1_aws-cdk@2.132.1/node_modules/@aws-quickstart/eks-blueprints/lib/addons/core-addon/index.ts:200:25)
      at VpcCniAddOn.deploy (node_modules/.pnpm/@aws-quickstart+eks-blueprints@1.14.0_aws-cdk-lib@2.132.1_aws-cdk@2.132.1/node_modules/@aws-quickstart/eks-blueprints/lib/addons/core-addon/index.ts:90:23)
          at async Promise.all (index 0)


ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/eks-blueprint/eks-cluster.test.ts.

      at Object.get [as CfnAddon] (node_modules/.pnpm/aws-cdk-lib@2.132.1_constructs@10.3.0/node_modules/aws-cdk-lib/aws-eks/index.js:1:2698)
      at VpcCniAddOn.deploy (node_modules/.pnpm/@aws-quickstart+eks-blueprints@1.14.0_aws-cdk-lib@2.132.1_aws-cdk@2.132.1/node_modules/@aws-quickstart/eks-blueprints/lib/addons/core-addon/index.ts:102:30)
          at async Promise.all (index 0)

  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "TypeError: aws_eks_1.CfnAddon is not a constructor
        at VpcCniAddOn.deploy (/Users/vudao/workspace/codecommit/cdk-typescript/aws-eks-blueprints-cdk/node_modules/.pnpm/@aws-quickstart+eks-blueprints@1.14.0_aws-cdk-lib@2.132.1_aws-cdk@2.132.1/node_modules/@aws-quickstart/eks-blueprints/lib/addons/core-addon/index.ts:102:26)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)".

      at VpcCniAddOn.deploy (node_modules/.pnpm/@aws-quickstart+eks-blueprints@1.14.0_aws-cdk-lib@2.132.1_aws-cdk@2.132.1/node_modules/@aws-quickstart/eks-blueprints/lib/addons/core-addon/index.ts:102:26)
          at async Promise.all (index 0)".
      at console.error (node_modules/.pnpm/@jest+console@29.7.0/node_modules/@jest/console/build/BufferedConsole.js:127:10)
      at node_modules/.pnpm/@aws-quickstart+eks-blueprints@1.14.0_aws-cdk-lib@2.132.1_aws-cdk@2.132.1/node_modules/@aws-quickstart/eks-blueprints/lib/stacks/eks-blueprint-stack.ts:308:21

/Users/vudao/workspace/codecommit/cdk-typescript/aws-eks-blueprints-cdk/node_modules/.pnpm/@aws-quickstart+eks-blueprints@1.14.0_aws-cdk-lib@2.132.1_aws-cdk@2.132.1/node_modules/@aws-quickstart/eks-blueprints/dist/stacks/eks-blueprint-stack.js:226
            throw new Error(err);
                  ^

Error: TypeError: aws_eks_1.CfnAddon is not a constructor
    at /Users/vudao/workspace/codecommit/cdk-typescript/aws-eks-blueprints-cdk/node_modules/.pnpm/@aws-quickstart+eks-blueprints@1.14.0_aws-cdk-lib@2.132.1_aws-cdk@2.132.1/node_modules/@aws-quickstart/eks-blueprints/lib/stacks/eks-blueprint-stack.ts:309:19
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Expected Behavior

No error

### Current Behavior

Got error 

### Reproduction Steps

```
npx jest --passWithNoTests --ci
```

### CDK CLI Version

2.132.1

### EKS Blueprints Version

1.14.0

### Node.js Version

v20.8.1

### Environment details (OS name and version, etc.)

Sonoma 14.3.1

**Comment by shapirov103** [comment]
@vumdao what tests are you running? We have internal snapshot/jest tests and all of them pass. 
If you are running your custom tests, then please take into account that addons can be async. The `ClusterAddOn` deploy signature is `deploy(clusterInfo: types.ClusterInfo): Promise<Construct>` - meaning it can return a promise. 

In 14.0 all core addons are now async as they use AWS SDK (async API) to lookup compatible version dynamically. 

To accommodate for this in your tests, please use async/await constructs. Example:

```ts
test("Coredns Addon deploying correct default version of Addon for 1.28", async () => { // async
    const app = new cdk.App();

    await blueprints.EksBlueprint.builder(). // await
        .account('123456789').region('us-west-2')
        .version(KubernetesVersion.V1_28)
        .addOns(new blueprints.CoreDnsAddOn("auto"))
        .buildAsync(app, "coredns-stack-001"); // buildAsync() should be used in the test
});
```

**Comment by vumdao** [comment]
This one https://github.com/aws-quickstart/cdk-eks-blueprints/issues/952 fixed the issue
