### ISSUE TITLE
(KomodorAddon): (Fails with synth errors)

### ISSUE THREAD

**Issue by elamaran11** [aws-quickstart/cdk-eks-blueprints#973]
### Describe the bug

Komodor Addon fails during synth

```
Building pattern komodor
INFO === Run make compile before each run, if any code modification was made. === 


WARN Upgrade is needed for chart k8s-watcher-1.3.4: latest version is 1.18.14.
TypeError: ts_deepmerge_1.default is not a function
    at KomodorAddOn.deploy (/Users/runner/work/cdk-eks-blueprints-patterns/cdk-eks-blueprints-patterns/node_modules/@komodor/komodor-eks-blueprints-addon/lib/index.ts:48:27)
    at new EksBlueprint (/Users/runner/work/cdk-eks-blueprints-patterns/cdk-eks-blueprints-patterns/node_modules/@aws-quickstart/eks-blueprints/lib/stacks/eks-blueprint-stack.ts:276:34)
    at BlueprintBuilder.build (/Users/runner/work/cdk-eks-blueprints-patterns/cdk-eks-blueprints-patterns/node_modules/@aws-quickstart/eks-blueprints/lib/stacks/eks-blueprint-stack.ts:204:16)
    at new KomodorConstruct (/Users/runner/work/cdk-eks-blueprints-patterns/cdk-eks-blueprints-patterns/lib/komodor-construct/index.ts:24:14)
    at Object.<anonymous> (/Users/runner/work/cdk-eks-blueprints-patterns/cdk-eks-blueprints-patterns/bin/komodor.ts:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module.m._compile (/Users/runner/work/cdk-eks-blueprints-patterns/cdk-eks-blueprints-patterns/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/runner/work/cdk-eks-blueprints-patterns/cdk-eks-blueprints-patterns/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
Error: TypeError: ts_deepmerge_1.default is not a function
    at /Users/runner/work/cdk-eks-blueprints-patterns/cdk-eks-blueprints-patterns/node_modules/@aws-quickstart/eks-blueprints/lib/stacks/eks-blueprint-stack.ts:309:19
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Expected Behavior

Addon should synthesize fine when used with Blueprints.

### Current Behavior

Komodor Addon fails during synth

```
Building pattern komodor
INFO === Run make compile before each run, if any code modification was made. === 


WARN Upgrade is needed for chart k8s-watcher-1.3.4: latest version is 1.18.14.
TypeError: ts_deepmerge_1.default is not a function
    at KomodorAddOn.deploy (/Users/runner/work/cdk-eks-blueprints-patterns/cdk-eks-blueprints-patterns/node_modules/@komodor/komodor-eks-blueprints-addon/lib/index.ts:48:27)
    at new EksBlueprint (/Users/runner/work/cdk-eks-blueprints-patterns/cdk-eks-blueprints-patterns/node_modules/@aws-quickstart/eks-blueprints/lib/stacks/eks-blueprint-stack.ts:276:34)
    at BlueprintBuilder.build (/Users/runner/work/cdk-eks-blueprints-patterns/cdk-eks-blueprints-patterns/node_modules/@aws-quickstart/eks-blueprints/lib/stacks/eks-blueprint-stack.ts:204:16)
    at new KomodorConstruct (/Users/runner/work/cdk-eks-blueprints-patterns/cdk-eks-blueprints-patterns/lib/komodor-construct/index.ts:24:14)
    at Object.<anonymous> (/Users/runner/work/cdk-eks-blueprints-patterns/cdk-eks-blueprints-patterns/bin/komodor.ts:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module.m._compile (/Users/runner/work/cdk-eks-blueprints-patterns/cdk-eks-blueprints-patterns/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/runner/work/cdk-eks-blueprints-patterns/cdk-eks-blueprints-patterns/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
Error: TypeError: ts_deepmerge_1.default is not a function
    at /Users/runner/work/cdk-eks-blueprints-patterns/cdk-eks-blueprints-patterns/node_modules/@aws-quickstart/eks-blueprints/lib/stacks/eks-blueprint-stack.ts:309:19
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Reproduction Steps

Add `KomodorAddOn` to list of Addons.

### CDK CLI Version

2.132.0

### EKS Blueprints Version

1.14.1

### Node.js Version

20.X.X

### Environment details (OS name and version, etc.)

Mac

**Comment by elamaran11** [comment]
@ronahk Can you look in to this issue?
